// Runtime SPIR-V shader loader for the vendored ggml-vulkan backend.
//
// Upstream ggml-vulkan.cpp expects a generated "ggml-vulkan-shaders.hpp"
// declaring, per shader, a `<name>_data`/`<name>_len` byte-array pair
// compiled directly into the binary (vulkan-shaders-gen's default output
// mode). This project deliberately never produces that header (same
// decision this fork already made for whisper.cpp's Vulkan backend, commit
// b0ab800 — a compiled-in embed of parakeet.cpp's own ggml v0.13.0 shader
// corpus runs well past 200MB of generated C++ source, vs. ~50-60MB as
// loose binary .spv files) — instead
// swift/Sources/parakeet_cpp/upstream/ggml-vulkan/vulkan-shaders/ ships the
// pre-compiled loose .spv files, and
// swift/Sources/parakeet_cpp/upstream/ggml-vulkan/ggml-vulkan-shaders.hpp
// (generated by scripts/gen-vulkan-shader-runtime.py, invoked from
// scripts/vendor-parakeet-cpp.sh) declares the exact same identifiers
// ggml-vulkan.cpp's call sites reference, but backed by the lazy_data /
// lazy_len proxy types below instead of compiled-in arrays: each one reads
// its corresponding .spv file into memory the first time it is used (i.e.
// the first time a Vulkan pipeline actually needs that shader — see
// ggml_vk_create_pipeline's call sites), then caches the bytes for the
// process lifetime.
//
// Base directory resolution, checked lazily on first shader load — NOT at
// static-init time, since static initializers run before Swift has had a
// chance to resolve the app bundle path. Highest priority first:
//   1. the SUPERDICTATE_VULKAN_SHADER_DIR environment variable, for
//      ad-hoc/test overrides — deliberately checked (and wins) even when
//      ggml_vk_shaders_set_directory() below has already been called,
//      since the scenario this env var exists for is redirecting an
//      already-configured, real shipped app at an alternate shader corpus
//      for debugging (a locally rebuilt .spv, a corpus with debug info,
//      etc.) without a rebuild — the one case where a lower-priority env
//      var would otherwise be permanently unreachable.
//   2. ggml_vk_shaders_set_directory(), if a Swift caller has already
//      invoked it (the shipped-app path: mirrors how ParakeetEngine.swift
//      resolves a model path via Bundle.main and passes it down as a plain
//      string into sd_parakeet_create).
//   3. a path relative to this file's own __FILE__ location on the machine
//      that compiled it — swift/Sources/parakeet_cpp/upstream/ggml-vulkan/
//      vulkan-shaders/ sits right next to this file in the vendored source
//      tree, so `swift run`/`swift build` dev builds (no .app bundle yet)
//      find the real shader corpus without any configuration.
#pragma once

// <stddef.h>/<stdint.h>, not the C++ <cstddef>/<cstdint>: this header is
// included from parakeet_cpp_module.h (the SwiftPM umbrella header),
// which Swift's Clang importer parses as plain C — the C++-only headers
// fail with "file not found" in that context (this fork already hit this
// exact bug for whisper_cpp's equivalent header, commit 14efc8d). Plain-C
// headers cover everything this file needs outside the __cplusplus-only
// block below.
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

// Configures the base directory containing the pre-compiled `<name>.spv`
// shader corpus (i.e. the directory that used to be
// swift/Sources/parakeet_cpp/upstream/ggml-vulkan/vulkan-shaders/ at build
// time — in a shipped app this is Contents/Resources/vulkan-shaders/,
// copied there by scripts/build-app.sh).
//
// Must be called before the first Vulkan pipeline is created (i.e. before
// ggml_backend_vk_init() / any ggml_vk_create_pipeline call), or the
// fallback resolution above takes over and shaders load from wherever this
// library happened to be compiled instead of the intended bundle. Safe to
// call more than once; the most recent call wins. Passing NULL or an empty
// string clears any previously configured directory and reverts to the
// environment-variable/source-relative fallbacks.
void ggml_vk_shaders_set_directory(const char * dir);

#ifdef __cplusplus
} // extern "C"

namespace ggml_vk_shaders_detail {

// Returns a pointer to the (cached, process-lifetime) loaded bytes of
// <name>.spv, or nullptr if the file could not be found/read (in which case
// get_len() below returns 0 too, and the failure is logged to stderr by the
// implementation — see ggml-vulkan-shaders-runtime.cpp's load_locked(). A
// misconfigured shader directory would otherwise mean EVERY shader silently
// passes a null pointer + zero size into vk::ShaderModuleCreateInfo with no
// guarantee Vulkan validation layers are even enabled to catch it in a
// shipped app, so this stderr line is the only diagnostic available for
// that failure mode — not merely a debugging nicety).
const void * get_data(const char * name);
uint64_t     get_len(const char * name);

// Lightweight proxy objects: hold only a `const char *` shader name (no
// dynamic allocation, trivially constexpr-constructible so the hundreds of
// generated globals in ggml-vulkan-shaders.cpp cost nothing at static-init
// time) and implicitly convert to the type ggml-vulkan.cpp's call sites
// actually consume (`const void *` / an integral length), triggering the
// cached-or-load-now lookup exactly at the point of use. This lets the
// generated header declare drop-in replacements for upstream's
// `<name>_data`/`<name>_len` C-array globals without having to rewrite any
// of ggml-vulkan.cpp's (heavily macro-generated) ggml_vk_create_pipeline(...)
// call sites — ggml-vulkan.cpp itself needs zero source edits.
class lazy_data {
public:
    explicit constexpr lazy_data(const char * name) : name_(name) {}
    operator const void *() const { return get_data(name_); }
private:
    const char * name_;
};

class lazy_len {
public:
    explicit constexpr lazy_len(const char * name) : name_(name) {}
    operator uint64_t() const { return get_len(name_); }
private:
    const char * name_;
};

} // namespace ggml_vk_shaders_detail
#endif
